name: 10-Controlling the Execution Flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: Whether unit tests will pass or not
        default: true
      Push-Artifact-To: 
        type: choice
        description: Where to push the artifact
        options: 
        - JFrog
        - Github

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building project"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Running unit tests
        run: echo "Running tests..."
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  build:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: Build Project
        run: echo "Building..."
  pushofartifact:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: push to jfrog
        if: ${{ inputs.Push-Artifact-To == 'JFrog'}} 
        run: echo "Pushing artifacto to ${{inputs.Push-Artifact-To}}"
      - name: push to github
        if: ${{ inputs.Push-Artifact-To == 'github'}} 
        run: echo "Pushing artifacto to ${{inputs.Push-Artifact-To}}"
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod..."
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running E2E tests
        run: echo "Running E2E tests"
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running load tests
        run: echo "Running load tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-tests
      - load-tests
    steps:
      - name: Deploying to prod
        run: echo "Deploying to prod..."


